In [2]:
import numpy as np 

In [4]:
my_list = [1, 2, 3, 4, 5]

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
zeros = np.zeros((2,4))

In [8]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones = np.ones((5,5))

In [10]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np_range = np.arange(0, 101, 2)

In [12]:
np_range

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
randm = np.random.random((2,5))

In [14]:
randm

array([[0.02803093, 0.86008582, 0.03110038, 0.83232589, 0.89499382],
       [0.06357718, 0.54010275, 0.20136116, 0.43169537, 0.87577872]])

In [16]:
randmn = np.random.randn(3, 5)

In [17]:
randmn

array([[-1.10922014,  1.80774349,  1.34098893, -1.85241479,  0.40556365],
       [ 0.13217561,  0.7429976 , -0.2188937 ,  0.6503118 ,  0.24175297],
       [-1.69698392,  1.15109853, -1.16260944, -1.82327827, -0.20729461]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.linspace(0, 5, 47)

array([0.        , 0.10869565, 0.2173913 , 0.32608696, 0.43478261,
       0.54347826, 0.65217391, 0.76086957, 0.86956522, 0.97826087,
       1.08695652, 1.19565217, 1.30434783, 1.41304348, 1.52173913,
       1.63043478, 1.73913043, 1.84782609, 1.95652174, 2.06521739,
       2.17391304, 2.2826087 , 2.39130435, 2.5       , 2.60869565,
       2.7173913 , 2.82608696, 2.93478261, 3.04347826, 3.15217391,
       3.26086957, 3.36956522, 3.47826087, 3.58695652, 3.69565217,
       3.80434783, 3.91304348, 4.02173913, 4.13043478, 4.23913043,
       4.34782609, 4.45652174, 4.56521739, 4.67391304, 4.7826087 ,
       4.89130435, 5.        ])

In [21]:
randmn.shape

(3, 5)

In [22]:
randmn.min()

-1.8524147931939405

In [23]:
randmn.max()

1.8077434898052962

In [24]:
randmn.argmax()

1

In [25]:
randmn.argmin()

3

In [26]:
randmn.dtype

dtype('float64')

In [28]:
arr_2d = np.arange(50).reshape(5, 10)

In [29]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arr_2d[3:,5:]

array([[35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

In [39]:
arr_2d[arr_2d > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [43]:
arr_2d % 3

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2, 0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2, 0, 1, 2, 0, 1]], dtype=int32)